# Generated by Django 4.2.4 on 2023-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('artists', models.JSONField()),
                ('duration', models.IntegerField()),
                ('image_url', models.URLField()),
                ('release_date', models.DateField()),
                ('added_at', models.DateField()),
            ],
        ),
    ]
